version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fluffy-funicular:latest
    restart: unless-stopped
    ports:
      - "80:8080"
    environment:
      PORT: "8080"
      # Laravel environment variables
      APP_ENV: "${APP_ENV:-production}"
      APP_KEY: "${APP_KEY}"
      APP_DEBUG: "${APP_DEBUG:-false}"
      # Database configuration (external/managed service)
      DB_CONNECTION: "${DB_CONNECTION:-pgsql}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT:-5432}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      # Redis configuration (external/managed service)
      REDIS_HOST: "${REDIS_HOST:-127.0.0.1}"
      REDIS_PASSWORD: "${REDIS_PASSWORD:-null}"
      REDIS_PORT: "${REDIS_PORT:-6379}"
      # Cache and session configuration
      CACHE_DRIVER: "${CACHE_DRIVER:-database}"
      SESSION_DRIVER: "${SESSION_DRIVER:-database}"
      QUEUE_CONNECTION: "${QUEUE_CONNECTION:-database}"
      # Deployment options
      AUTO_MIGRATE: "${AUTO_MIGRATE:-true}"
    working_dir: /app

# No volumes needed for production deployment
